// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://boayjmtjlivfppobtelm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvYXlqbXRqbGl2ZnBwb2J0ZWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTk2NjYsImV4cCI6MjA1ODczNTY2Nn0.ZyNIgWW5XLysT_a8RG-lIjIWu7R6EPu3ecrF_6odTFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);